### ISSUE TITLE
Player can't shoot fireballs during movement

### ISSUE THREAD

**Issue by o-farag** [lipskii198/XQGame-#10]
When holding down the movement buttons or being in midair, the player can't shoot fireballs.

**Comment by lipskii198** [comment]
this was an intended feature that got obsolete, if you want to change it you can go to the player controller script and change the canAttack function deleating the requirements you think aren't needed anymore 
![image](https://github.com/lipskii198/XQGame-/assets/114819835/cfc56e10-984b-4977-a1fb-258fe7c50d80)

**Comment by 0xRoco** [comment]
no longer a problem with the new controller
