### ISSUE TITLE
Moving causes xqc sprite to change

### ISSUE THREAD

**Issue by o-farag** [lipskii198/XQGame-#7]
![spritemovebug](https://user-images.githubusercontent.com/15898988/229646329-bad17bc6-7083-4b03-a8eb-795e3311eb31.gif)

**Comment by 0xRoco** [comment]
caused by flip value mismatching with the prefab it self

![image](https://user-images.githubusercontent.com/43659330/229650169-cf0fdb98-84ae-47eb-82d9-73a4a23602f6.png)
![image](https://user-images.githubusercontent.com/43659330/229650197-13bc79bb-3c2e-4bed-bc09-16ca40a8a917.png)
