### ISSUE TITLE
Shooting fireball gives NullReferenceException

### ISSUE THREAD

**Issue by o-farag** [lipskii198/XQGame-#8]
Attempting to shoot a fireball on AntsLevel throws an exception.

```
NullReferenceException: Object reference not set to an instance of an object
Managers.SpellsManager.Cast (System.String spellName) (at Assets/Scripts/Managers/SpellsManager.cs:29)
PlayerController.BeginAttack () (at Assets/Scripts/PlayerController.cs:116)
PlayerController.Update () (at Assets/Scripts/PlayerController.cs:40)
```

![image](https://user-images.githubusercontent.com/15898988/229646926-1ebcf886-c09b-415d-8a16-2dc02bc9c11b.png)

**Comment by 0xRoco** [comment]
should be fixed in [ae8c37a](https://github.com/lipskii198/XQGame-/commit/ae8c37ad1806a6e321d96406ab8445ccee548db8)

**Comment by o-farag** [comment]
@0xRoco I have the latest changes, I think it's because I played the scene directly instead of loading it from the main menu. Is that how it's supposed to be?

**Comment by 0xRoco** [comment]
Oh in that case yes that's expected since ObjectPoolManager is not Initialized

**Comment by o-farag** [comment]
Alright, closing
